/* 
 * This project is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/
 * Any copyright is dedicated to the NominalNimbus.
 * https://github.com/NominalNimbus 
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptingService.TradingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName= "TradingService.IWCFConnection", CallbackContract=typeof(ScriptingService.TradingService.IWCFCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IWCFConnection {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFConnection/Login", ReplyAction="http://tempuri.org/IWCFConnection/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerCommonObjects.TradingServerException), Action="http://tempuri.org/IWCFConnection/LoginTradingServerExceptionFault", Name="TradingServerException", Namespace="http://schemas.datacontract.org/2004/07/ServerCommonObjects")]
        ServerCommonObjects.LoginResponse Login(ServerCommonObjects.LoginRequest message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFConnection/Login", ReplyAction="http://tempuri.org/IWCFConnection/LoginResponse")]
        System.Threading.Tasks.Task<ServerCommonObjects.LoginResponse> LoginAsync(ServerCommonObjects.LoginRequest message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IWCFConnection/LogOut")]
        void LogOut();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IWCFConnection/LogOut")]
        System.Threading.Tasks.Task LogOutAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/IWCFConnection/MessageIn")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.GetDataFeedListRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.SubscribeRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.UnsubscribeRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.HistoryDataRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.HeartbeatRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.OrdersListRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.PlaceOrderRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.CancelOrderRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ModifyOrderRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.TradingInfoRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.BrokersLoginRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.BrokerLogoutRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.PortfolioActionRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.BrokersAvailableSecuritiesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.AddUserFilesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.RemoveUserFilesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.CreateUserIndicatorRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.CreateUserSignalRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.SignalDataRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.BacktestResultsRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.SaveScriptingDataRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.SignalActionRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.UpdateStrategyParamsRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.RemoveScriptingInstanceRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingReportRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.GetLastTickRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.StartedSignalExecutionRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.LoginRequest))]
        void MessageIn(ServerCommonObjects.RequestMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsInitiating=false, Action="http://tempuri.org/IWCFConnection/MessageIn")]
        System.Threading.Tasks.Task MessageInAsync(ServerCommonObjects.RequestMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFConnection/RegisterProcessor", ReplyAction="http://tempuri.org/IWCFConnection/RegisterProcessorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerCommonObjects.TradingServerException), Action="http://tempuri.org/IWCFConnection/RegisterProcessorTradingServerExceptionFault", Name="TradingServerException", Namespace="http://schemas.datacontract.org/2004/07/ServerCommonObjects")]
        void RegisterProcessor(ServerCommonObjects.RegisterUCProcessorResponse message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFConnection/RegisterProcessor", ReplyAction="http://tempuri.org/IWCFConnection/RegisterProcessorResponse")]
        System.Threading.Tasks.Task RegisterProcessorAsync(ServerCommonObjects.RegisterUCProcessorResponse message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFConnection/MessageOut")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingOutput))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.GetDataFeedListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.HistoryDataResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.TickDataResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.HeartbeatResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ErrorMessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.AccountInfoChangedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.HistoricalOrdersListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.OrdersUpdatedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.OrdersChangedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.TradingInfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.BrokerLoginResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.BrokersAvailableSecuritiesResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.PositionChangedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.BrokerLogoutResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.PortfolioActionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.OrderRejectionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.PositionUpdatedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.HistoricalOrderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.SignalDataResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingDataSavedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingInstanceCreatedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.IndicatorSeriesUpdatedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingMessageResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingExitResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingInstanceUnloadedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingDataRemoveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.SignalActionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.BacktestReportMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.ScriptingReportResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.GetLastTickResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.RegisterUCProcessorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.StartSignalExecutionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.StopSignalExecutionResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServerCommonObjects.LoginResponse))]
        void MessageOut(ServerCommonObjects.ResponseMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFConnectionChannel : ScriptingService.TradingService.IWCFConnection, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFConnectionClient : System.ServiceModel.DuplexClientBase<ScriptingService.TradingService.IWCFConnection>, ScriptingService.TradingService.IWCFConnection {
        
        public WCFConnectionClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WCFConnectionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WCFConnectionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFConnectionClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFConnectionClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public ServerCommonObjects.LoginResponse Login(ServerCommonObjects.LoginRequest message) {
            return base.Channel.Login(message);
        }
        
        public System.Threading.Tasks.Task<ServerCommonObjects.LoginResponse> LoginAsync(ServerCommonObjects.LoginRequest message) {
            return base.Channel.LoginAsync(message);
        }
        
        public void LogOut() {
            base.Channel.LogOut();
        }
        
        public System.Threading.Tasks.Task LogOutAsync() {
            return base.Channel.LogOutAsync();
        }
        
        public void MessageIn(ServerCommonObjects.RequestMessage message) {
            base.Channel.MessageIn(message);
        }
        
        public System.Threading.Tasks.Task MessageInAsync(ServerCommonObjects.RequestMessage message) {
            return base.Channel.MessageInAsync(message);
        }
        
        public void RegisterProcessor(ServerCommonObjects.RegisterUCProcessorResponse message) {
            base.Channel.RegisterProcessor(message);
        }
        
        public System.Threading.Tasks.Task RegisterProcessorAsync(ServerCommonObjects.RegisterUCProcessorResponse message) {
            return base.Channel.RegisterProcessorAsync(message);
        }
    }
}
